### ISSUE TITLE
Insert an appropriate footer

### ISSUE THREAD

**Issue by hs-07** [hs-07/magic_notes#1]

**Comment by 21omkarsase** [comment]
Hey @hs-07 I would like to contribute.
Assign this to me.

**Comment by hs-07** [comment]
@21omkarsase 
Sure. go ahead
Fork the repo and yaa dont forget to star it✨😊

**Comment by 21omkarsase** [comment]
I have made changes in code
Should I do PR now ?

![1](https://user-images.githubusercontent.com/77478864/195182231-b6f0e909-da17-42d5-912e-bbf3974d52ec.png)
![2](https://user-images.githubusercontent.com/77478864/195182243-d35d9db6-0a7e-4a74-8dce-a20bc9e4f3cc.png)

**Comment by hs-07** [comment]
@21omkarsase 
yaa u can open PR it looks nice.

**Comment by 21omkarsase** [comment]
Yes, Done.
Please review it.

**Comment by hs-07** [comment]
I had mergered your PR but your changes arent reflected in the site.
@21omkarsase 
did this PR is showing on your hacktoberfest profile?

**Comment by 21omkarsase** [comment]
Yes.It is showing there.
![Screenshot_20221012-113819](https://user-images.githubusercontent.com/77478864/195263469-3503815e-a71f-4448-8c52-98098771d63b.png)

Also chages are made on your repository.
If you are looking on your local system confirm that you  have pulled code from remote repo

**Comment by hs-07** [comment]
Can you make an another PR but with same code?
@21omkarsase 
as you can seen in the website link that your changes are not reflecting.
And i dont want that after 6 days your PR which is in waiting, gets rejected

**Comment by 21omkarsase** [comment]
> Can you make an another PR but with same code? @21omkarsase as you can seen in the website link that your changes are not reflecting. And i dont want that after 6 days your PR which is in waiting, gets rejected

Yes, I have opened a PR regarding footer.
Please review it.

When I did first pull request after that you merged your revert-3-main branch with main branch.
![1](https://user-images.githubusercontent.com/77478864/195418059-d7ab8d27-96d8-4a66-ab9a-9cd414ebc715.png)

I think because of that changes made by me were not reflecting in main branch

**Comment by 21omkarsase** [comment]
> Can you make an another PR but with same code? @21omkarsase as you can seen in the website link that your changes are not reflecting. And i dont want that after 6 days your PR which is in waiting, gets rejected

Hii @hs-07, you can try github-pages for deployment to get rid of this problem.
