### ISSUE TITLE
Create a Contact Page

### ISSUE THREAD

**Issue by hs-07** [hs-07/magic_notes#2]
- Create an html page name as about.html.
- Create a form.
- Insert functionality like when user inserts data, that data is receive me on my Email _{harshitcr7777@gmail.com}_
- Make the page responsive.

Ask if any problem you face.

**Comment by Abhishek3223** [comment]
hey can i work on it

**Comment by karnikagupta30** [comment]
@hs-07 can you assign me this issue?

**Comment by hs-07** [comment]
assigned @tokyo3001 
Get started 😊
fork the repo, and yaa dont forget to star it 🙌✨

**Comment by Hiresh23** [comment]
i would like to contribute

**Comment by Hiresh23** [comment]
please assign

**Comment by hs-07** [comment]
@Hiresh23 
The issue is already been assigned . 
But u can explore more in the project and raise more issue.
Thank you

**Comment by hs-07** [comment]
@Hiresh23 
Now you can try this issue
