### ISSUE TITLE
search button size and icon

### ISSUE THREAD

**Issue by Hiresh23** [hs-07/magic_notes#6]

**Comment by Hiresh23** [comment]
i would like to contribute to this

**Comment by 21omkarsase** [comment]
Hey @hs-07, I have made appropriate changes for search button.
Should I do PR ?

https://user-images.githubusercontent.com/77478864/195428079-6339ba49-da9d-43e2-934f-a69975b7b220.mp4

**Comment by hs-07** [comment]
@21omkarsase Yes
